package gui;
import java.awt.*;
import java.awt.event.*;

import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;

/**
 * This program makes an awt window containing a JFreeChart ChartPanel which
 * shows the height of a few liquids in a capillary for various radiuses.
 * The series are generated by clicking on the left "+" button and filling
 * the module.
 *
 */

public class MainWindow extends Frame{
	
	/**
	 * Literally the Main Window, contains a SideContainer, a button on top to add new liquids and
	 * a ChartPanel 
	 */
	private static final long serialVersionUID = 4654752977065080419L;
	
	private SideContainer sidePane = new SideContainer();
	
	MainWindow(){
		
		setTitle("Grafici!");
		setLayout(new BorderLayout());
		add(sidePane, BorderLayout.WEST);
		add(sidePane.getLiquidAdder(), BorderLayout.NORTH);
		setSize(500, 300);
		
		JFreeChart xylineChart = ChartFactory.createXYLineChart(
	        "" ,
	        "Radius (cm)",
	        "Heigth (cm)",sidePane.getDataset(),
	        PlotOrientation.VERTICAL,
	        true , true , false);
		
		ChartPanel chartPanel = new ChartPanel( xylineChart );
		
		add(chartPanel, BorderLayout.CENTER);
		
		//closes the program if the close button on the top bar is pressed
		addWindowListener(new WindowAdapter(){
		public void windowClosing(WindowEvent we)
			{
			System.exit(0);
			}
		});
		setVisible(true);
		
	};

	public static void main(String args[]){  
		@SuppressWarnings("unused")
		MainWindow mainWindow = new MainWindow();  
	}
}